---
title: "P8105 HW5"
author: "Hansheng Zhang"
date: 2021-11-19
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(p8105.datasets)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1
This problem is about homicides in 50 large U.S. cities. The data comes from _The Washington Post_. The solution comes from Jeff's echo recording.

```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na = c("", "uknown")) %>% 
  mutate(city_state = str_c(city, state),
  resolution = case_when(
    disposition == "Closed without arrest" ~ "unsolved",
    disposition == "Open/No arrest"        ~ "unsolved",
    disposition == "Closed by arrest"      ~ "solved"
  )) %>% 
  relocate(city_state)
```

Focusing on Baltimore, MD
```{r, baltimore_df}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")
baltimore_summary =
  baltimore_df %>% 
  summarise(
    unsolved = sum(resolution == "unsolved"),
    n = n()
    )
baltimore_test = 
  prop.test(
    x = baltimore_summary %>% pull(unsolved),
    n = baltimore_summary %>% pull(n))
baltimore_test %>% 
  broom::tidy() %>% 
  knitr::kable()
```


```{r, prop_test_function}
prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>% 
      summarise(
        unsolved = sum(resolution == "unsolved"),
        n = n()
      )
  
  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
    )
  
  return(city_test)
  
}
# trying for another city 
homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function() %>% 
  broom::tidy() %>% 
  knitr::kable()
```


```{r, iteration}
results_df = 
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
    ) %>% 
    select(city_state, tidy_results) %>% 
    unnest(tidy_results) %>% 
    select(city_state, estimate, starts_with("conf"))
head(results_df) %>% 
  knitr::kable()
```


```{r}
results_df %>% 
  filter(city_state != "TulsaAL") %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +  
  theme(axis.text.x = element_text(size = 7, angle = 90, vjust = 0.5, hjust = 1))
  
``` 
